name: Java CI with Gradle

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Corrected usage of `uses` attribute
    - name: Set up JDK 17
      uses: actions/setup-java@v2  # Corrected usage of `uses` attribute
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test
      run: ./gradlew test  # Corrected usage of `run` for running Gradle task
